version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  driverag:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
      # - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped